[book]
authors = ["SrRéquiem"]
description = "Libro de notas donde encontrarás cada truco/técnica/guía de hacking que he aprendido y recolectado de CTFS, aplicaciones reales, lectura de writeups y noticias."
language = "es"
multilingual = false
src = "src"
title = "Secronomicón"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
site-url = "/Secronomicon/"